### ISSUE TITLE
youtube creator matched with Wikidata

### ISSUE THREAD

**Issue by salgo60** [derenrich/borked-bot#4]
I am playing around with outdoor gyms see [Wikidata:WikiProject_Outdoor_Gyms](https://www.wikidata.org/wiki/Wikidata:WikiProject_Outdoor_Gyms)

One user case I can see is to see what videos [are connected to an outdoor gym](https://w.wiki/3fKJ) 
* see number of views on those videos [see query](https://www.wikidata.org/wiki/Wikidata:WP_OGyms/Query_examples#using_metadata_from_Youtube_-_map)
* see who produced the video i,e, is it an influencer, the government to see what videos get most views 
  * I guess in Wikidata we have "YouTube channel ID" [Property:P2397](https://www.wikidata.org/wiki/Property:P2397) that can be associated with an organisation/person

-->
**Feature request:** could we also get the account creating the video ? Best would be to match this account to a WIkidata account
* the people doing [Scholia](https://scholia.toolforge.org/)  has solved the problem that not every person is in Wikidata for authors by using 
  * [Property:P50](https://www.wikidata.org/wiki/Property:P50) "author"
  * [Property:P2093](https://www.wikidata.org/wiki/Property:P2093)"author name string" when the author is not matched with Wikidata

Thanks
[user Salgo60](https://www.wikidata.org/wiki/User:Salgo60) on WD

**Comment by derenrich** [comment]
Can you edit an item with how you think the bot should be updating the items in this case and link me to the diff? you want a qualifier on the youtube video with the uploader? what property do you think that should be?

**Comment by salgo60** [comment]
Thanks I do a try and will try to check with more people e.g. @Ainali

----
- Video: [bi5NsdQS43I](https://www.youtube.com/watch?v=bi5NsdQS43I)
is about 
- Wikidata [Q107208319](https://www.wikidata.org/wiki/Q107208319)

Today we have:
![image](https://user-images.githubusercontent.com/14206509/126743540-1ccfa05a-99d5-4f3d-8629-6c28792d6b33.png)


My suggestion is add also [Property:P2397](https://www.wikidata.org/wiki/Property:P2397) "YouTube channel ID"

![image](https://user-images.githubusercontent.com/14206509/126743322-e5b72bba-be0f-46dd-b234-45ab3ab77185.png)

i.e. 
- Video [bi5NsdQS43I](https://www.youtube.com/watch?v=bi5NsdQS43I) is part of "YouTube channel" [UCaIBKiUqH3cmRbb530-Ue2A](https://www.youtube.com/channel/UCaIBKiUqH3cmRbb530-Ue2A)

**User Story:**
As an user on Wikidata I would like to be able to see **who has produced a video** so that we can see the differencies of impact(nr of views) when different groups publish videos on a subject

**Comment by Ainali** [comment]
> My suggestion is add also [Property:P2397](https://www.wikidata.org/wiki/Property:P2397) "YouTube channel ID"

Oh, I like this idea, it would make it much easier to figure out the value of a single video and also make it possible to query for all videos in Wikidata by channel.

**Comment by derenrich** [comment]
ok so it sounds like as a first step you want videos tagged with the youtube channel they come from. that is easy enough though we'll have to change the set of allowed qualifiers on youtube videos. do you also want me to add a qualifier linking the video to the author item? that is harder and could be done at query time in SPARQL

**Comment by Ainali** [comment]
Yes, tagging the videos with the youtube channel is enough. No need to add the author explicitly as that query wouldn't be that hard.

**Comment by derenrich** [comment]
Ok the bot is updated to tag with the youtube channel. Here is the example edit: https://www.wikidata.org/w/index.php?title=Q240478&type=revision&diff=1464906124&oldid=1463818534 and the code for the change is https://github.com/derenrich/borked-bot/commit/6ac291d39b26f67b0af207b8a3f4165ff1d49ed5

Going back and filling this in for all existing videos will take a while though and my bot is engaged in a task that will take about 20 days so doing that will have to wait. Re-open this ticket if I forget to do it.
